export type GeoSubmission = {
  id: string;
  created_at: string;
  updated_at: string;
  full_name: string;
  work_email: string;
  company_name: string;
  website_url: string;
  phone: string | null;
  primary_service: string | null;
  service_area: string | null;
  industry: string | null;
  business_size: string | null;
  main_goal: string | null;
  competitors: string | null;
  cms_platform: string | null;
  current_challenges: string | null;
  access_available: string | null;
  selected_plan: string | null;
  notes: string | null;
  status: string;
  current_plan?: string | null;
  previous_plan?: string | null;
  next_plan?: string | null;
  subscription_status?: string | null;
  billing_provider?: string | null;
  billing_customer_id?: string | null;
  billing_subscription_id?: string | null;
  next_billing_at?: string | null;
  cancel_at_period_end?: boolean | null;
  canceled_at?: string | null;
  cancellation_reason?: string | null;
  cancellation_reason_detail?: string | null;
  downgrade_reason?: string | null;
  pause_until?: string | null;
  save_offer_shown?: string | null;
  save_offer_accepted?: boolean | null;
  health_status?: string | null;
  churn_risk_level?: string | null;
  payment_issue_status?: string | null;
  last_report_viewed_at?: string | null;
  last_summary_viewed_at?: string | null;
  last_engagement_at?: string | null;
  retention_last_event_at?: string | null;
  winback_eligible?: boolean | null;
  follow_up_status?: string | null;
  recommended_offer?: string | null;
  confirmation_email_sent_at?: string | null;
  report_email_sent_at?: string | null;
  follow_up_day_1_sent_at?: string | null;
  follow_up_day_3_sent_at?: string | null;
  follow_up_day_5_sent_at?: string | null;
  follow_up_day_7_sent_at?: string | null;
  booked_review_at?: string | null;
  converted_at?: string | null;
  follow_up_stopped_at?: string | null;
  last_contacted_at?: string | null;
  admin_notified_at?: string | null;
  results_token?: string | null;
};

export type GeoAuditJob = {
  id: string;
  submission_id: string;
  created_at: string;
  updated_at: string;
  status: string;
  started_at: string | null;
  completed_at: string | null;
  failed_at: string | null;
  failure_reason: string | null;
  audit_version: string;
  review_required?: boolean;
  published_at?: string | null;
};

export type GeoAuditResult = {
  id: string;
  submission_id: string;
  audit_job_id: string;
  created_at: string;
  updated_at?: string;
  summary: string | null;
  executive_summary?: string | null;
  customer_headline?: string | null;
  customer_executive_summary?: string | null;
  strengths_json?: unknown;
  scorecard_json: Record<string, unknown> | null;
  findings_json: Record<string, unknown> | null;
  recommendations_json: Record<string, unknown> | null;
  next_step_json: Record<string, unknown> | null;
  limitations_json?: unknown;
  crawl_notes_json?: unknown;
};

export type GeoFixPreview = {
  id: string;
  submission_id: string;
  audit_job_id: string;
  created_at: string;
  type: string;
  title: string;
  issue_summary: string;
  why_it_matters: string;
  before_text: string | null;
  after_text: string;
  html_preview: string | null;
  evidence_urls: string[];
  priority: string;
  implementation_effort: string;
  status: string;
};

export type GeoInternalFix = {
  id: string;
  submission_id: string;
  audit_job_id: string;
  related_finding_label: string | null;
  related_finding_category: string | null;
  type: string;
  title: string;
  issue_summary: string;
  why_it_matters: string;
  affected_urls: string[];
  generated_content: Record<string, unknown>;
  generated_html: string | null;
  generated_json: Record<string, unknown> | null;
  implementation_notes: string | null;
  implementation_effort: string;
  priority: string;
  confidence: string;
  status: string;
  internal_only: boolean;
  customer_visible: boolean;
  created_by_system: boolean;
  internal_note: string | null;
  promoted_preview_id: string | null;
  created_at: string;
  updated_at: string;
};

export type GeoResultAccessToken = {
  id: string;
  submission_id: string;
  audit_job_id: string | null;
  token_hash: string;
  created_at: string;
  expires_at: string | null;
  revoked_at: string | null;
  last_accessed_at: string | null;
};

export type GeoAdminNote = {
  id: string;
  submission_id: string;
  author_email: string;
  created_at: string;
  note: string;
};

export type GeoSubscriptionEvent = {
  id: string;
  submission_id: string;
  event_name: string;
  old_plan: string | null;
  new_plan: string | null;
  cancellation_reason: string | null;
  save_offer_type: string | null;
  initiated_by: string;
  effective_at: string | null;
  metadata_json: Record<string, unknown>;
  created_at: string;
};

export type ResultsBundle = {
  submission: GeoSubmission;
  job: GeoAuditJob;
  result: GeoAuditResult | null;
  previews: GeoFixPreview[];
};

export type GeoMockupLead = {
  id: string;
  created_at: string;
  updated_at: string;
  website_url: string;
  business_name: string;
  business_category: string;
  preferred_style: string;
  homepage_goal: string;
  notes: string | null;
  email: string | null;
  lead_source: string;
  concept_json: Record<string, unknown>;
  signals_json: Record<string, unknown> | null;
  access_token_hash: string;
  result_viewed_at: string | null;
  subscription_cta_clicked_at: string | null;
  selected_plan_intent: string | null;
  status: string;
};
