export const siteConfig = {
  name: "Grand Strand Ally",
  description: "Information technology cost clarity, practical support, and compliance-minded systems for small and medium businesses in the Grand Strand and Myrtle Beach area.",
  email: "shawn@gsally.com",
  phone: "973-202-1455",
  serviceArea: "Grand Strand / Myrtle Beach, SC",
  links: {
    home: "/",
    services: "/services",
    pricing: "/pricing",
    contact: "/contact",
    contactForm: "/contact#contact-form",
    costAnalysis: "/cost-analysis",
    privacy: "/privacy",
    terms: "/terms",
    managedItSupport: "/managed-it-support-myrtle-beach",
    microsoft365SupportPage: "/microsoft-365-support",
    networkWifiManagement: "/network-wifi-management-myrtle-beach",
    itCostAnalysis: "/it-cost-analysis",
    cybersecurityCompliancePage: "/cybersecurity-compliance-support",
    backupRecoverySupportPage: "/backup-recovery-support",
    onboardingOffboardingAutomation: "/onboarding-offboarding-automation",
    geo: "/generative-engine-optimization",
    geoAudit: "/geo-audit",
    geoAssessment: "https://gsageo.vercel.app/",
  }
};
